version: '3'

services:
  app:
    build: .
    container_name: app
    restart: always
    volumes:
      - data:/usr/local/apache2/htdocs/
    networks:
      - app-network
  
  webserver:
    image: httpd:2.4
    container_name: server
    restart: always
    volumes:
      - data:/usr/local/apache2/htdocs/
    ports:
      - "8000:80"
    networks:
      - app-network
  repository:
    image: sonatype/nexus3:3.41.1
    container_name: nexus
    restart: always
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8091:8081"
      - "8123:8123"
    networks:
      - app-network

networks:
  app-network:
volumes:
  data:
  nexus-data: