---
- hosts: localhost
  become: true
  gather_facts: no
  tasks:
  - name: Aguardando servidor
    wait_for_connection:
      delay: 10
      timeout: 15
      
  - name: Update apt
    remote_user: ubuntu
    apt:
      update_cache: yes

  - name: install jdk
    remote_user: ubuntu
    apt:
      name: openjdk-11-jre
      state: present
    become: true

  - name: install wget
    remote_user: ubuntu
    apt:
      name: wget
      state: latest
    become: true

  - name: Instalando git
    remote_user: ubuntu
    apt:
      name: ['git']
      state: present
    become: true

  - name: jenkins apt repository key is installed
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present
    become: yes
  
  - name: repository is configured
    apt_repository:
      repo: 'deb https://pkg.jenkins.io/debian-stable binary'
      state: present
    become: yes
  
  - name: Update apt
    remote_user: ubuntu
    apt:
      update_cache: yes

  - name: jenkins is installed
    remote_user: ubuntu
    apt:
      name: jenkins
        update_cache: yes
      become: yes

  - name: jenkins is ruuning
    service:
      name: jenkins
      state: started

  - name: Instalando docker
    remote_user: ubuntu
    apt:
      name: ['docker.io', 'docker-compose']
      state: present
    become: true

  - name: Adicionando usuario ubuntu no grupo docker
    remote_user: ubuntu
    user:
      name: "ubuntu"
      group: "docker"
      append: yes
    tags:
      - docker
  
  - name: Adicionando usuario jenkins no grupo docker
    remote_user: ubuntu
    user:
      name: "jenkins"
      group: "docker"
      append: yes
    tags:
      - docker

  - name: jenkins restart
    service:
      name: jenkins
      state: restarted
    
  - name: Clonando Repositorio
    git:
      repo: https://github.com/thisiscaetano/web-app.git
      dest: /home/ubuntu/web-app
  
